[package]
name = "vulkano-shaders"
version = "0.3.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
repository = "https://github.com/tomaka/vulkano"
description = "Shaders "
license = "MIT/Apache-2.0"
documentation = "http://tomaka.github.io/vulkano/vulkano/index.html"

[dependencies]
glsl-to-spirv = { version = "0.1.0", path = "../glsl-to-spirv" }
