[package]
name = "vulkano-shader-derive"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]

[lib]
name = "vulkano_shader_derive"
proc-macro = true

[dependencies]
glsl-to-spirv = { version = "0.1.2", path = "../glsl-to-spirv" }
syn = { version = "0.10", features = ["aster", "visit"] }
vulkano-shaders = { version = "0.3", path = "../vulkano-shaders" }
