[package]
name = "vulkano"
version = "0.1.0"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
build = "build.rs"
description = "Safe wrapper for the Vulkan graphics API"

[dependencies]
crossbeam = "0.2.5"
shared_library = "0.1.4"
#smallvec = "0.1.6"
smallvec = { git = "https://github.com/servo/rust-smallvec" }
lazy_static = "0.1.15"

[build-dependencies]
vk-sys = { path = "../vk-sys" }
vulkano-shaders = { path = "../vulkano-shaders" }

[dev-dependencies]
cgmath = "0.7.0"
image = "0.6.1"
winit = { git = "https://github.com/tomaka/winit" }
